version: '3.4'

services:
  db:
    image: mysql:8.0
    container_name: mysql_server_db
    ports:
        - 3306:3306
    environment:
        - MYSQL_ROOT_PASSWORD=1234

  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi\Dockerfile
    environment:
      DefaultConnection: "Server=172.21.0.1;DataBase=Tryitter;Uid=root;Pwd=1234"